### PR TITLE
Fallback to project servers

### PR DESCRIPTION
**Pull request by svaante**
Excellent package :)  Simple ergonomics improvement, being able to search for symbol without having to open an buffer which is associated with an eglot server.

When using `consult-eglot' outside of buffer with a cached server, fallback to the first server in project supporting symbol search.

### CODE REVIEW

**Review by mohkale — COMMENTED** [review]
I like the idea, but wonder if maybe we could support searches across all servers at once rather than just the first server supporting the symbol providers feature :thinking:.

**Comment by svaante** [comment]
Great idea! See last commit

**Review by mohkale — APPROVED** [review]
I wonder if the server callback is thread safe :thinking:, but as a whole I think this is an improvement. Thanks. Now I just need to find a project with two servers that support this so I can test it :upside_down_face:.

**Comment by svaante** [comment]
They are as you say thread safe,  the do not run at separate threads but on the same thread but different timer callbacks.

The stack would look something like the following for two requests.

-> Request 1
-> Request 2

<- First response (could be either of the requests, dependent on which server respond first)
<- Second response

**Pull request merged**
